### ISSUE TITLE
403了耶

### ISSUE THREAD

**Issue by wolfan** [ustclug/telegram-web#2]

**Comment by gaoyifan** [comment]
由于众所周知的原因，服务已关闭。

**Comment by wolfan** [comment]
@gaoyifan 还有机会恢复么？

**Comment by gaoyifan** [comment]
@wolfan 如有需要，建议自行搭建。

**Comment by wolfan** [comment]
那个能问下，你那个短信是怎么转发的呐？

**Comment by gaoyifan** [comment]
什么短信？

**Comment by wolfan** [comment]
@gaoyifan 就是telegram的验证码，是怎么实现转发的呐？

**Comment by gaoyifan** [comment]
请参考这篇文档： https://github.com/freedocs/docs/blob/master/使用nginx反向代理telegram网页客户端(单域名).md <https://github.com/freedocs/docs/blob/master/%E4%BD%BF%E7%94%A8nginx%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86telegram%E7%BD%91%E9%A1%B5%E5%AE%A2%E6%88%B7%E7%AB%AF(%E5%8D%95%E5%9F%9F%E5%90%8D).md>

**Comment by wolfan** [comment]
@gaoyifan 谢谢😍😍😍
